-- 创建训练设置表
CREATE TABLE IF NOT EXISTS workout_setting (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
    intro_video_reps INT DEFAULT NULL COMMENT 'intro video 次数',
    intro_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'intro audio 对应 sound id',
    intro_audio_start_time INT DEFAULT NULL COMMENT 'intro audio 开始时间(秒)',
    intro_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'intro audio 是否可关闭',
    preview_video_reps INT DEFAULT NULL COMMENT 'preview video 次数',
    preview_first_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview first audio 对应 sound id',
    preview_first_audio_start_time INT DEFAULT NULL COMMENT 'preview first audio 开始时间(秒)',
    preview_first_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview first audio 是否可关闭',
    preview_next_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview next audio 对应 sound id',
    preview_next_audio_start_time INT DEFAULT NULL COMMENT 'preview next audio 开始时间(秒)',
    preview_next_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview next audio 是否可关闭',
    preview_last_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview last audio 对应 sound id',
    preview_last_audio_start_time INT DEFAULT NULL COMMENT 'preview last audio 开始时间(秒)',
    preview_last_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview last audio 是否可关闭',
    preview_name_audio_start_time INT DEFAULT NULL COMMENT 'preview name audio 开始时间(秒)',
    preview_name_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview name audio 是否可关闭',
    preview_three_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview 3 audio 对应 sound id',
    preview_three_audio_end_time INT DEFAULT NULL COMMENT 'preview 3 audio 结束时间(秒)',
    preview_three_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview 3 audio 是否可关闭',
    preview_two_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview 2 audio 对应 sound id',
    preview_two_audio_end_time INT DEFAULT NULL COMMENT 'preview 2 audio 结束时间(秒)',
    preview_two_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview 2 audio 是否可关闭',
    preview_one_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'preview 1 audio 对应 sound id',
    preview_one_audio_end_time INT DEFAULT NULL COMMENT 'preview 1 audio 结束时间(秒)',
    preview_one_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview 1 audio 是否可关闭',
    preview_rest_audio_start_time INT DEFAULT NULL COMMENT 'preview rest audio 开始时间(秒)',
    preview_rest_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'preview rest audio 是否可关闭',
    execution_go_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution go audio 对应 sound id',
    execution_go_audio_start_time INT DEFAULT NULL COMMENT 'execution go audio 开始时间(秒)',
    execution_go_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution go audio 是否可关闭',
    execution_video_reps INT DEFAULT NULL COMMENT 'execution video 次数',
    execution_guidance_audio_start_time INT DEFAULT NULL COMMENT 'execution guidance audio 开始时间(秒)',
    execution_guidance_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution guidance audio 是否可关闭',
    execution_halfway_audio_start_time INT DEFAULT NULL COMMENT 'execution halfway audio 开始时间(秒)',
    execution_halfway_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution halfway audio 是否可关闭',
    execution_three_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution 3 audio 对应 sound id',
    execution_three_audio_end_time INT DEFAULT NULL COMMENT 'execution 3 audio 结束时间(秒)',
    execution_three_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution 3 audio 是否可关闭',
    execution_two_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution 2 audio 对应 sound id',
    execution_two_audio_end_time INT DEFAULT NULL COMMENT 'execution 2 audio 结束时间(秒)',
    execution_two_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution 2 audio 是否可关闭',
    execution_one_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution 1 audio 对应 sound id',
    execution_one_audio_end_time INT DEFAULT NULL COMMENT 'execution 1 audio 结束时间(秒)',
    execution_one_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution 1 audio 是否可关闭',
    execution_beep_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution beep audio 对应 sound id',
    execution_beep_audio_end_time INT DEFAULT NULL COMMENT 'execution beep audio 结束时间(秒)',
    execution_beep_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution beep audio 是否可关闭',
    execution_rest_audio_biz_sound_id BIGINT DEFAULT NULL COMMENT 'execution rest audio 对应 sound id',
    execution_rest_audio_end_time INT DEFAULT NULL COMMENT 'execution rest audio 结束时间(秒)',
    execution_rest_audio_closed TINYINT(1) DEFAULT 0 COMMENT 'execution rest audio 是否可关闭',
    execution_halfway_audio_biz_sound_ids JSON DEFAULT NULL COMMENT 'execution halfway audio 对应 sound id 数组',
    intro_video_cycle_code VARCHAR(50) DEFAULT NULL COMMENT 'intro Video Cycle',
    preview_video_cycle_code VARCHAR(50) DEFAULT NULL COMMENT 'preview Video Cycle',
    execution_video_cycle_code VARCHAR(50) DEFAULT NULL COMMENT 'execution Video Cycle',
    status ENUM('DRAFT', 'ENABLED', 'DISABLED') NOT NULL DEFAULT 'DRAFT' COMMENT '状态',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_status (status),
    INDEX idx_is_deleted (is_deleted)
) COMMENT='训练设置表';
